
package es.unican.ss.ssestimacionparadastus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IEstimacionParadasTUS", targetNamespace = "http://www.unican.es/ss/SSEstimacionParadasTUS")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IEstimacionParadasTUS {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns es.unican.ss.ssestimacionparadastus.EstimacionTUS
     * @throws ParadaNoValidaException_Exception
     * @throws DatosNoDisponiblesException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEstimacionSiguienteBus", targetNamespace = "http://www.unican.es/ss/SSEstimacionParadasTUS", className = "es.unican.ss.ssestimacionparadastus.GetEstimacionSiguienteBus")
    @ResponseWrapper(localName = "getEstimacionSiguienteBusResponse", targetNamespace = "http://www.unican.es/ss/SSEstimacionParadasTUS", className = "es.unican.ss.ssestimacionparadastus.GetEstimacionSiguienteBusResponse")
    @Action(input = "http://www.unican.es/ss/SSEstimacionParadasTUS/IEstimacionParadasTUS/getEstimacionSiguienteBusRequest", output = "http://www.unican.es/ss/SSEstimacionParadasTUS/IEstimacionParadasTUS/getEstimacionSiguienteBusResponse", fault = {
        @FaultAction(className = ParadaNoValidaException_Exception.class, value = "http://www.unican.es/ss/SSEstimacionParadasTUS/IEstimacionParadasTUS/getEstimacionSiguienteBus/Fault/ParadaNoValidaException"),
        @FaultAction(className = DatosNoDisponiblesException_Exception.class, value = "http://www.unican.es/ss/SSEstimacionParadasTUS/IEstimacionParadasTUS/getEstimacionSiguienteBus/Fault/DatosNoDisponiblesException")
    })
    public EstimacionTUS getEstimacionSiguienteBus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws DatosNoDisponiblesException_Exception, ParadaNoValidaException_Exception
    ;

}
