
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DinamicaSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DinamicaSoap {


    /**
     * Ultimo error
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetLastError", action = "http://tempuri.org/GetLastError")
    @WebResult(name = "GetLastErrorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetLastError", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLastError")
    @ResponseWrapper(localName = "GetLastErrorResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLastErrorResponse")
    public String getLastError();

    /**
     * Eventos de cabecera
     * 
     * @param sec
     * @param parada
     * @param linea
     * @return
     *     returns org.tempuri.ArrayOfInfoHeaderEvent
     */
    @WebMethod(operationName = "GetEvents", action = "http://tempuri.org/GetEvents")
    @WebResult(name = "GetEventsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetEvents", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEvents")
    @ResponseWrapper(localName = "GetEventsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEventsResponse")
    public ArrayOfInfoHeaderEvent getEvents(
        @WebParam(name = "linea", targetNamespace = "http://tempuri.org/")
        String linea,
        @WebParam(name = "sec", targetNamespace = "http://tempuri.org/")
        int sec,
        @WebParam(name = "parada", targetNamespace = "http://tempuri.org/")
        int parada);

    /**
     * Vehiculos de la Linea
     * 
     * @param pass
     * @param linea
     * @return
     *     returns org.tempuri.ArrayOfInfoVehiculo
     */
    @WebMethod(operationName = "XGetVehiculos", action = "http://tempuri.org/XGetVehiculos")
    @WebResult(name = "XGetVehiculosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "XGetVehiculos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.XGetVehiculos")
    @ResponseWrapper(localName = "XGetVehiculosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.XGetVehiculosResponse")
    public ArrayOfInfoVehiculo xGetVehiculos(
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "linea", targetNamespace = "http://tempuri.org/")
        String linea);

    /**
     * Vehiculos de la Linea
     * 
     * @param linea
     * @return
     *     returns org.tempuri.ArrayOfInfoVehiculo
     */
    @WebMethod(operationName = "GetVehiculos", action = "http://tempuri.org/GetVehiculos")
    @WebResult(name = "GetVehiculosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetVehiculos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVehiculos")
    @ResponseWrapper(localName = "GetVehiculosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVehiculosResponse")
    public ArrayOfInfoVehiculo getVehiculos(
        @WebParam(name = "linea", targetNamespace = "http://tempuri.org/")
        String linea);

    /**
     * Coches de la Linea
     * 
     * @param pass
     * @param linea
     * @return
     *     returns org.tempuri.ArrayOfInfoCoche
     */
    @WebMethod(operationName = "XGetCoches", action = "http://tempuri.org/XGetCoches")
    @WebResult(name = "XGetCochesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "XGetCoches", targetNamespace = "http://tempuri.org/", className = "org.tempuri.XGetCoches")
    @ResponseWrapper(localName = "XGetCochesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.XGetCochesResponse")
    public ArrayOfInfoCoche xGetCoches(
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "linea", targetNamespace = "http://tempuri.org/")
        String linea);

    /**
     * Coches de la Linea
     * 
     * @param linea
     * @return
     *     returns org.tempuri.ArrayOfInfoCoche
     */
    @WebMethod(operationName = "GetCoches", action = "http://tempuri.org/GetCoches")
    @WebResult(name = "GetCochesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCoches", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCoches")
    @ResponseWrapper(localName = "GetCochesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCochesResponse")
    public ArrayOfInfoCoche getCoches(
        @WebParam(name = "linea", targetNamespace = "http://tempuri.org/")
        String linea);

    /**
     * Estimacion de paso por parada
     * 
     * @param pass
     * @param xGetPasoParadaResult
     * @param parada
     * @param linea
     * @param status
     */
    @WebMethod(operationName = "XGetPasoParada", action = "http://tempuri.org/XGetPasoParada")
    @RequestWrapper(localName = "XGetPasoParada", targetNamespace = "http://tempuri.org/", className = "org.tempuri.XGetPasoParada")
    @ResponseWrapper(localName = "XGetPasoParadaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.XGetPasoParadaResponse")
    public void xGetPasoParada(
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "linea", targetNamespace = "http://tempuri.org/")
        String linea,
        @WebParam(name = "parada", targetNamespace = "http://tempuri.org/")
        String parada,
        @WebParam(name = "status", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<Integer> status,
        @WebParam(name = "XGetPasoParadaResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfPasoParada> xGetPasoParadaResult);

    /**
     * Estimacion de paso por parada
     * 
     * @param parada
     * @param getPasoParadaResult
     * @param linea
     * @param status
     */
    @WebMethod(operationName = "GetPasoParada", action = "http://tempuri.org/GetPasoParada")
    @RequestWrapper(localName = "GetPasoParada", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPasoParada")
    @ResponseWrapper(localName = "GetPasoParadaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPasoParadaResponse")
    public void getPasoParada(
        @WebParam(name = "linea", targetNamespace = "http://tempuri.org/")
        String linea,
        @WebParam(name = "parada", targetNamespace = "http://tempuri.org/")
        String parada,
        @WebParam(name = "status", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<Integer> status,
        @WebParam(name = "GetPasoParadaResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfPasoParada> getPasoParadaResult);

    /**
     * Estimacion de paso por parada y registra en BD
     * 
     * @param pass
     * @param parada
     * @param xGetPasoParadaREGResult
     * @param medio
     * @param linea
     * @param status
     */
    @WebMethod(operationName = "XGetPasoParadaREG", action = "http://tempuri.org/XGetPasoParadaREG")
    @RequestWrapper(localName = "XGetPasoParadaREG", targetNamespace = "http://tempuri.org/", className = "org.tempuri.XGetPasoParadaREG")
    @ResponseWrapper(localName = "XGetPasoParadaREGResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.XGetPasoParadaREGResponse")
    public void xGetPasoParadaREG(
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "linea", targetNamespace = "http://tempuri.org/")
        String linea,
        @WebParam(name = "parada", targetNamespace = "http://tempuri.org/")
        String parada,
        @WebParam(name = "medio", targetNamespace = "http://tempuri.org/")
        int medio,
        @WebParam(name = "status", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<Integer> status,
        @WebParam(name = "XGetPasoParadaREGResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfPasoParada> xGetPasoParadaREGResult);

    /**
     * Estimacion de paso por parada y registra en BD
     * 
     * @param getPasoParadaREGResult
     * @param parada
     * @param medio
     * @param linea
     * @param status
     */
    @WebMethod(operationName = "GetPasoParadaREG", action = "http://tempuri.org/GetPasoParadaREG")
    @RequestWrapper(localName = "GetPasoParadaREG", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPasoParadaREG")
    @ResponseWrapper(localName = "GetPasoParadaREGResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPasoParadaREGResponse")
    public void getPasoParadaREG(
        @WebParam(name = "linea", targetNamespace = "http://tempuri.org/")
        String linea,
        @WebParam(name = "parada", targetNamespace = "http://tempuri.org/")
        String parada,
        @WebParam(name = "medio", targetNamespace = "http://tempuri.org/")
        int medio,
        @WebParam(name = "status", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<Integer> status,
        @WebParam(name = "GetPasoParadaREGResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfPasoParada> getPasoParadaREGResult);

    /**
     * Estado de la Linea
     * 
     * @param linea
     * @return
     *     returns org.tempuri.LineStatusInfo
     */
    @WebMethod(operationName = "GetStatusLinea", action = "http://tempuri.org/GetStatusLinea")
    @WebResult(name = "GetStatusLineaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStatusLinea", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStatusLinea")
    @ResponseWrapper(localName = "GetStatusLineaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStatusLineaResponse")
    public LineStatusInfo getStatusLinea(
        @WebParam(name = "linea", targetNamespace = "http://tempuri.org/")
        String linea);

    /**
     * Estado de las Lineas
     * 
     * @param lineas
     * @return
     *     returns org.tempuri.ArrayOfLineStatusInfo
     */
    @WebMethod(operationName = "GetStatusLineas", action = "http://tempuri.org/GetStatusLineas")
    @WebResult(name = "GetStatusLineasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStatusLineas", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStatusLineas")
    @ResponseWrapper(localName = "GetStatusLineasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStatusLineasResponse")
    public ArrayOfLineStatusInfo getStatusLineas(
        @WebParam(name = "lineas", targetNamespace = "http://tempuri.org/")
        ArrayOfString lineas);

    /**
     * Acciones por linea
     * 
     * @param macro
     * @param coche
     * @param vehiculo
     * @param linea
     * @return
     *     returns org.tempuri.ArrayOfInfoAccion
     */
    @WebMethod(operationName = "GetAcciones", action = "http://tempuri.org/GetAcciones")
    @WebResult(name = "GetAccionesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAcciones", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAcciones")
    @ResponseWrapper(localName = "GetAccionesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAccionesResponse")
    public ArrayOfInfoAccion getAcciones(
        @WebParam(name = "macro", targetNamespace = "http://tempuri.org/")
        int macro,
        @WebParam(name = "linea", targetNamespace = "http://tempuri.org/")
        int linea,
        @WebParam(name = "coche", targetNamespace = "http://tempuri.org/")
        int coche,
        @WebParam(name = "vehiculo", targetNamespace = "http://tempuri.org/")
        int vehiculo);

    /**
     * Informacion adicional de vehiculos
     * 
     * @param coche
     * @param vehiculo
     * @param linea
     * @return
     *     returns org.tempuri.InfoVehiculoExt
     */
    @WebMethod(operationName = "GetInfoVehiculo", action = "http://tempuri.org/GetInfoVehiculo")
    @WebResult(name = "GetInfoVehiculoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetInfoVehiculo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInfoVehiculo")
    @ResponseWrapper(localName = "GetInfoVehiculoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInfoVehiculoResponse")
    public InfoVehiculoExt getInfoVehiculo(
        @WebParam(name = "linea", targetNamespace = "http://tempuri.org/")
        String linea,
        @WebParam(name = "coche", targetNamespace = "http://tempuri.org/")
        int coche,
        @WebParam(name = "vehiculo", targetNamespace = "http://tempuri.org/")
        int vehiculo);

    /**
     * getactividades
     * 
     * @param svccond
     * @param svcbus
     * @param cond
     * @return
     *     returns org.tempuri.ArrayOfActividadesInfo
     */
    @WebMethod(operationName = "GetInfoActividades", action = "http://tempuri.org/GetInfoActividades")
    @WebResult(name = "GetInfoActividadesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetInfoActividades", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInfoActividades")
    @ResponseWrapper(localName = "GetInfoActividadesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInfoActividadesResponse")
    public ArrayOfActividadesInfo getInfoActividades(
        @WebParam(name = "svcbus", targetNamespace = "http://tempuri.org/")
        String svcbus,
        @WebParam(name = "svccond", targetNamespace = "http://tempuri.org/")
        String svccond,
        @WebParam(name = "cond", targetNamespace = "http://tempuri.org/")
        int cond);

}
