
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Dinamica", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://www.ayto-santander.es:9001/services/dinamica.asmx?wsdl")
public class Dinamica
    extends Service
{

    private final static URL DINAMICA_WSDL_LOCATION;
    private final static WebServiceException DINAMICA_EXCEPTION;
    private final static QName DINAMICA_QNAME = new QName("http://tempuri.org/", "Dinamica");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.ayto-santander.es:9001/services/dinamica.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DINAMICA_WSDL_LOCATION = url;
        DINAMICA_EXCEPTION = e;
    }

    public Dinamica() {
        super(__getWsdlLocation(), DINAMICA_QNAME);
    }

    public Dinamica(WebServiceFeature... features) {
        super(__getWsdlLocation(), DINAMICA_QNAME, features);
    }

    public Dinamica(URL wsdlLocation) {
        super(wsdlLocation, DINAMICA_QNAME);
    }

    public Dinamica(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DINAMICA_QNAME, features);
    }

    public Dinamica(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Dinamica(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DinamicaSoap
     */
    @WebEndpoint(name = "DinamicaSoap")
    public DinamicaSoap getDinamicaSoap() {
        return super.getPort(new QName("http://tempuri.org/", "DinamicaSoap"), DinamicaSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DinamicaSoap
     */
    @WebEndpoint(name = "DinamicaSoap")
    public DinamicaSoap getDinamicaSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "DinamicaSoap"), DinamicaSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DINAMICA_EXCEPTION!= null) {
            throw DINAMICA_EXCEPTION;
        }
        return DINAMICA_WSDL_LOCATION;
    }

}
