
package es.unican.ss.volumenArea;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VolumenAreaInterface", targetNamespace = "http://www.unican.es/ss/VolumenArea/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VolumenAreaInterface {


    /**
     * Retorna el area del objeto dado
     * 
     * @param params
     * @return
     *     returns double
     * @throws DatosNoValidosException
     */
    @WebMethod(action = "http://www.unican.es/ss/VolumenArea/area")
    @WebResult(name = "areaResponse", targetNamespace = "http://www.unican.es/ss/VolumenArea/types/", partName = "params")
    public double area(
        @WebParam(name = "area", targetNamespace = "http://www.unican.es/ss/VolumenArea/types/", partName = "params")
        Dimensiones params)
        throws DatosNoValidosException
    ;

    /**
     * Retorna el volumen del objeto dado 
     * 
     * @param params
     * @return
     *     returns double
     * @throws DatosNoValidosException
     */
    @WebMethod(action = "http://www.unican.es/ss/VolumenArea/volumen")
    @WebResult(name = "volumenResponse", targetNamespace = "http://www.unican.es/ss/VolumenArea/types/", partName = "params")
    public double volumen(
        @WebParam(name = "volumen", targetNamespace = "http://www.unican.es/ss/VolumenArea/types/", partName = "params")
        Dimensiones params)
        throws DatosNoValidosException
    ;

}
